version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-patch']
  labels:
  - dependencies
