version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  reviewers:
    - driesd
    - ArnaudWeyts
    - lowiebenoot
    - sanderbrugge
    - JorenSaeyTL
    - lorgan3
    - EOSullivanBerlin
    - timdegroote
  labels:
  - dependencies
